const data = [
    {
      img: "../assets/images/product_images/traditional_art/madhubani_art/1678953220188Ram -Sita.png",
      title: "Ram Vivah",
      prevPrice: "3600",
      newPrice: "4032",
      category: "traditionalart",
    },
    {
      img: "../assets/images/product_images/traditional_art/madhubani_art/1615571146923Bird.jpg",
      title: "Birds The Symbol Of Love",
      prevPrice: "2000",
      newPrice: "1904",
      category: "traditionalart",
    },
    {
      img: "../assets/images/product_images/traditional_art/banglar_patachitra/1678953122984Tea costar.jpeg",
      title: "Beautiful Tea Coaster",
      prevPrice: "400",
      newPrice: "336",
      category: "traditionalart",
    },
    {
      img: "../assets/images/product_images/traditional_art/banglar_patachitra/1678952913470Patachitra.jpeg",
      title: "Patachitra Painting",
      prevPrice: "750",
      newPrice: "672",
      category: "traditionalart",
    },
    {
      img: "../assets/images/product_images/traditional_craft/1678949318901B.jpg",
      title: "Tribal Lady",
      prevPrice: "700",
      newPrice: "548",
      category: "traditionalcraft",
    },
    {
      img: "../assets/images/product_images/traditional_craft/1613716745869walnut.jpg",
      title: "Walnut Wood Tissue Box",
      prevPrice: "3550",
      newPrice: "2783",
      category: "traditionalcraft",
    },
    {
      img: "../assets/images/product_images/indian_saree/1676319418496A.jpeg",
      title: "Banarasi Silk Saree",
      prevPrice: "5000",
      newPrice: "4987",
      category: "indiansaree",
    },
    {
      img: "../assets/images/product_images/indian_saree/1676316784448A.png",
      title: "Santipur Tant Saree",
      prevPrice: "900",
      newPrice: "756",
      category: "indiansaree",
    },
    {
      img: "../assets/images/product_images/indian_saree/1676318530893A.jpeg",
      title: "Dhaniakhali Dobby Buti Saree",
      prevPrice: "1300",
      newPrice: "955",
      category: "indiansaree",
    },
    {
      img: "../assets/images/product_images/indian_saree/1678127700738C.jpeg",
      title: "Shatal Karwati Saree",
      prevPrice: "10500",
      newPrice: "9922",
      category: "indiansaree",
    },
    {
      img: "../assets/images/product_images/indian_saree/1676316305547A.jpg",
      title: "Phulkari Saree",
      prevPrice: "2470",
      newPrice: "2334",
      category: "indiansaree",
    },
    {
      img: "../assets/images/product_images/dupatta/1678951930718H.jpeg",
      title: "Phulkari Dupatta",
      prevPrice: "825",
      newPrice: "693",
      category: "dupatta",
    },
    {
      img: "../assets/images/product_images/dupatta/1610605956573patachitra dupatta.jpeg",
      title: "Patachitra Dupatta",
      prevPrice: "1000",
      newPrice: "892",
      category: "dupatta",
    },
    {
      img: "../assets/images/product_images/shawl/1618056561332pashmina.jpg",
      title: "Pashmina Shawl",
      prevPrice: "70000",
      newPrice: "69825",
      category: "shawl",
    },
    {
      img: "../assets/images/product_images/shawl/1619204701363banana.jpg",
      title: "Kani Shawl",
      prevPrice: "2240",
      newPrice: "1881",
      category: "shawl",
    },
    {
      img: "../assets/images/product_images/shawl/1678950105303F.jpg",
      title: "Phulkari Shawl",
      prevPrice: "1330",
      newPrice: "1117",
      category: "shawl",
    },
    {
      img: "../assets/images/product_images/grocery/1616520737707agarbatti.jpg",
      title: "Mysore Sandal Agarbatti",
      prevPrice: "120",
      newPrice: "94",
      category: "grocery",
    },
    {
      img: "../assets/images/product_images/grocery/1607622048831mysore sandal soap.jpg",
      title: "Mysore Sandal Soap",
      prevPrice: "300",
      newPrice: "230",
      category: "grocery",
    },
    {
      img: "../assets/images/product_images/grocery/1617726622353Black Tea.jpg",
      title: "Darjeeling Tea",
      prevPrice: "1200",
      newPrice: "1134",
      category: "grocery",
    },
    {
      img: "../assets/images/product_images/grocery/1616406204330tulaipanji  .jpg",
      title: "Tulaipanji Rice",
      prevPrice: "1000",
      newPrice: "945",
      category: "grocery",
    },
    {
      img: "../assets/images/product_images/sweets/1618634393321Rosogolla.jpg",
      title: "Banglar Rosogolla",
      prevPrice: "500",
      newPrice: "413",
      category: "sweets",
    },
    {
      img: "../assets/images/product_images/sweets/1618634393321Rosogolla.jpg",
      title: "Banglar Rosogolla",
      prevPrice: "500",
      newPrice: "413",
      category: "sweets",
    },
    {
      img: "../assets/images/product_images/clay_craft/1619420247770terracotta.jpg",
      title: "Elephant Pair Terracotta",
      prevPrice: "6000",
      newPrice: "5376",
      category: "claycraft",
    },
    {
      img: "../assets/images/product_images/clay_craft/1619202961553ganesh-ji.jpg",
      title: "Chhau Mask Ganesh Ji",
      prevPrice: "900",
      newPrice: "756",
      category: "claycraft",
    },
    {
      img: "../assets/images/product_images/clay_craft/1608104376989bowl-600x600.jpg",
      title: "Khurja pottery bowl lamp",
      prevPrice: "700",
      newPrice: "689",
      category: "claycraft",
    },
    {
      img: "../assets/images/product_images/wooden_craft/1617733888247light.jpg",
      title: "Saharanpur Light",
      prevPrice: "800",
      newPrice: "761",
      category: "woodencraft",
    },
    {
      img: "../assets/images/product_images/wooden_craft/1616406824249walnut a .jpg",
      title: "Walnut Wood Carving Bowl",
      prevPrice: "2700",
      newPrice: "2661",
      category: "woodencraft",
    },
    {
      img: "../assets/images/product_images/metal_craft/1617653174946moradabad a.jpg",
      title: "Copper Bottles and Glasses",
      prevPrice: "1499",
      newPrice: "1415",
      category: "metalcraft",
    },
]

